
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: age_detection_container
    volumes:
      - .:/app
    environment:
      - POETRY_VIRTUALENVS_IN_PROJECT=true
    command: ["poetry", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

    ports:
      - "8000:8000"  # if using a web server like FastAPI or Django

  test:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - POETRY_VIRTUALENVS_IN_PROJECT=true
    volumes:
      - .:/app
    command: ["poetry", "run", "pytest", "--cov=app", "--cov-report=term-missing", "-v"]
